version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: accounts
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: accounts

	accounts:
		build: .
		image: chamaconekt/accounts
		links:
		- postgres
		container_name: accounts
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- accounts
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/accounts-nginx/nginx.conf
		depends_on:
			- accounts
		ports:
			- 80:80
		volumes_from:
			- accounts

volumes:
	accounts-static-files:
		driver:local